Remove all `package-lock.json` from test-programs
Since we started using the right version of `@pulumi/pulumi-gcp` for
NodeJS program testing, we are getting `test-programs` runtime errors
related to pinned old dependencies which are incompatible with the
latest and greatest `@pulumi/pulumi` and `@pulumi/pulimi-gcp` versions.
For instance, we observed the following `grpc`-related error:

```
Error: 13 INTERNAL: Request message serialization failure: b.Va is not a function
```

By removing the `package-lock.json` files, we are letting transitive
dependencies float--we are no longer pinning dependencies--and letting
`npm`/`yarn` determine which versions to use. Now, package managers
should correctly resolve which dependencies are compatible, and we
should no longer observe any runtime failures.